### PR TITLE
Change floor image to one of the competition floor.

### PR DESCRIPTION
**Pull request by aftersomemath**
Floor is a transformed screened shot from an iarc 2016 video of the competition floor.

https://www.youtube.com/watch?v=_gSpkFBMsh0

### CODE REVIEW

**Comment by amiller27** [comment]
I think we should have multiple floors to choose from that are easily switchable.  I did start adding more in some stuff that I haven't committed yet, but right now I have them as different materials that can be switched in environment.blend.  Also, that screenshot shouldn't be in the repo.

**Comment by aftersomemath** [comment]
The screenshot is actually the gimp transform if someone wanted to make tweaks. It can be renamed and put in a different folder.

I like that idea. However is it easier to switch the image file than do it in the .blend?

**Comment by amiller27** [comment]
Not if you want different material properties.  For the screenshot, I would say rename it.  The images need to be put in a folder anyway.

**Comment by aftersomemath** [comment]
Can we close this and create a trello item?

**Comment by amiller27** [comment]
Yes

**Pull request closed without merging**
